[[news]]
date = "2026-4"
content = "Our work GSSIP has been accepted to R:SS 2026. I will present the work orally in Sydney! 🎉"

[[news]]
date = "2024-8"
content = "Starting my PhD at the National University of Singapore"
