type = "card"
title = "Teaching"
description = "Courses I have taught or assisted with."

[[items]]
title = "CS5340 Uncertainty Modelling in AI"
subtitle = "Teaching Assistant"
date = "2026"
content = "CS5340 is about how to “represent” and “reason” with uncertainty in a computer."
tags = ["Master-Level", "CS"]
